#!/usr/bin/env python3
"""Static docs generator for jddavenport.com/docs.

Python 3 standard library only. No pip packages, no build step on Vercel:
run this locally, commit the generated docs/ tree, deploy as usual.

    python3 tools/docs/build.py            # build docs/ + update sitemap.xml
    python3 tools/docs/build.py --quiet
    python3 tools/docs/check.py            # then gate it

Inputs:
    tools/docs/sections.json               ordered [{id,title,description,groups?}]
    tools/docs/content/<section>/<slug>.md front matter + a small Markdown subset

Outputs (everything under docs/ that carries GENERATED_MARK is owned here):
    docs/index.html                        landing
    docs/<section>/index.html              section landing
    docs/<section>/<slug>/index.html       article
    docs/docs.css, docs/docs.js            copied from tools/docs/assets/
    docs/search-index.json                 client-side search index
    sitemap.xml                            docs URLs replaced, other entries kept

The build is deterministic (no timestamps), writes a file only when its bytes
change, and deletes stale pages it generated earlier. It never deletes a file
that lacks GENERATED_MARK and never touches anything outside docs/ except the
docs block of sitemap.xml.
"""
from __future__ import annotations

import argparse
import html
import json
import math
import os
import re
import shutil
import sys
from dataclasses import dataclass, field
from pathlib import Path

HERE = Path(__file__).resolve().parent
ROOT = HERE.parent.parent
DEFAULT_SECTIONS = HERE / "sections.json"
DEFAULT_CONTENT = HERE / "content"
ASSETS = HERE / "assets"
OUT = ROOT / "docs"
SITEMAP = ROOT / "sitemap.xml"

SITE = "https://jddavenport.com"
OG_IMAGE = f"{SITE}/images/og-image.png"
GENERATED_MARK = "<!-- generated by tools/docs/build.py; edit the Markdown source, not this file -->"
ALLOWED_KEYS = {"title", "description", "section", "group", "order", "updated", "sources"}
REQUIRED_KEYS = ("title", "description", "section", "order", "updated")
SLUG_RE = re.compile(r"^[a-z0-9]+(?:-[a-z0-9]+)*$")
DATE_RE = re.compile(r"^\d{4}-\d{2}-\d{2}$")
WORDS_PER_MIN = 230
CALLOUTS = ("Note", "Warning", "Tip")


# --------------------------------------------------------------------------
# Front matter
# --------------------------------------------------------------------------

class SourceError(Exception):
    pass


def _parse_scalar(raw: str):
    v = raw.strip()
    if not v:
        return ""
    if v.startswith('"'):
        try:
            return json.loads(v)
        except json.JSONDecodeError as e:
            raise SourceError(f"bad double-quoted value {v!r}: {e}") from None
    if v.startswith("'"):
        if not v.endswith("'") or len(v) < 2:
            raise SourceError(f"unterminated single-quoted value {v!r}")
        return v[1:-1].replace("''", "'")
    if v.startswith("["):
        try:
            return json.loads(v)
        except json.JSONDecodeError:
            inner = v[1:-1] if v.endswith("]") else v[1:]
            items = [p.strip() for p in inner.split(",") if p.strip()]
            return [_parse_scalar(p) if p[0] in "\"'" else p for p in items]
    if re.fullmatch(r"-?\d+", v):
        return int(v)
    return v


def parse_front_matter(text: str):
    """Return (meta dict, body str). Raises SourceError on a malformed file."""
    text = text.replace("\r\n", "\n").lstrip("﻿")
    m = re.match(r"^---\n(.*?)\n---[ \t]*\n?(.*)$", text, re.S)
    if not m:
        raise SourceError("no front matter block (--- ... ---) at top of file")
    meta = {}
    for ln, line in enumerate(m.group(1).split("\n"), 2):
        if not line.strip() or line.lstrip().startswith("#"):
            continue
        km = re.match(r"^([A-Za-z_][\w-]*)\s*:\s*(.*)$", line)
        if not km:
            raise SourceError(f"front matter line {ln} is not 'key: value': {line!r}")
        meta[km.group(1)] = _parse_scalar(km.group(2))
    return meta, m.group(2)


# --------------------------------------------------------------------------
# Markdown subset -> HTML
# --------------------------------------------------------------------------

FENCE_RE = re.compile(r"^(\s*)(`{3,}|~{3,})\s*([\w+#.-]*)\s*$")
HEADING_RE = re.compile(r"^\s{0,3}(#{1,6})\s+(.*?)\s*#*\s*$")
HR_RE = re.compile(r"^\s{0,3}([-*_])(?:\s*\1){2,}\s*$")
LIST_RE = re.compile(r"^(\s*)([-*+]|\d{1,9}[.)])(\s+)(.*)$")
TABLE_SEP_RE = re.compile(r"^\s*\|?\s*:?-{2,}:?\s*(\|\s*:?-{2,}:?\s*)*\|?\s*$")
QUOTE_RE = re.compile(r"^\s{0,3}>\s?(.*)$")
URL_RE = re.compile(r"https?://[^\s<>\"'`]+")


def indent_of(line: str) -> int:
    return len(line) - len(line.lstrip(" "))


def slugify(text: str) -> str:
    s = re.sub(r"<[^>]+>", "", text)
    s = html.unescape(s).lower()
    s = re.sub(r"[`*_\[\]()]", "", s)
    s = re.sub(r"[^a-z0-9]+", "-", s).strip("-")
    return s or "section"


def strip_inline_md(text: str) -> str:
    """Plain text of an inline Markdown string (for ids, TOC, search)."""
    t = re.sub(r"\[([^\]]+)\]\([^)]*\)", r"\1", text)
    t = re.sub(r"\\([\\`*_\[\]|>#-])", r"\1", t)
    t = t.replace("`", "")
    t = re.sub(r"\*\*(.+?)\*\*", r"\1", t)
    t = re.sub(r"(?<![\w*])\*(?!\s)(.+?)(?<!\s)\*(?![\w*])", r"\1", t)
    return t


@dataclass
class RenderCtx:
    ids: dict = field(default_factory=dict)
    toc: list = field(default_factory=list)        # [(level, id, text)]
    links: list = field(default_factory=list)      # every href written
    warnings: list = field(default_factory=list)

    def unique_id(self, base: str) -> str:
        n = self.ids.get(base, 0)
        self.ids[base] = n + 1
        return base if n == 0 else f"{base}-{n + 1}"


def _link_attrs(url: str, ctx: RenderCtx) -> str:
    ctx.links.append(url)
    href = html.escape(url, quote=True)
    if re.match(r"^https?://", url) and not url.startswith(SITE + "/docs"):
        return f'href="{href}" target="_blank" rel="noopener"'
    return f'href="{href}"'


LINK_RE = re.compile(r"\[((?:[^\[\]]|\[[^\[\]]*\])+)\]\(\s*((?:[^()\s]|\([^()\s]*\))+)\s*\)")


def render_inline(text: str, ctx: RenderCtx, allow_links: bool = True) -> str:
    slots: list[str] = []

    def put(s: str) -> str:
        slots.append(s)
        return f"\x00{len(slots) - 1}\x00"

    # 1. backslash escapes
    t = re.sub(r"\\([\\`*_\[\]()|>#!-])", lambda m: put(html.escape(m.group(1))), text)
    # 2. code spans (any run of backticks, matched to an equal run)
    t = re.sub(r"(`+)(.+?)(?<!`)\1(?!`)",
               lambda m: put(f"<code>{html.escape(m.group(2).strip() if m.group(2).strip() else m.group(2))}</code>"), t)
    # 3. links
    if allow_links:
        def link(m):
            label = render_inline(m.group(1), ctx, allow_links=False)
            return put(f"<a {_link_attrs(m.group(2), ctx)}>{label}</a>")
        t = LINK_RE.sub(link, t)

        # 4. bare URLs
        def bare(m):
            url = m.group(0)
            trail = ""
            while url and url[-1] in ".,;:!?*_":
                trail = url[-1] + trail
                url = url[:-1]
            while url.endswith(")") and url.count(")") > url.count("("):
                trail = ")" + trail
                url = url[:-1]
            return put(f"<a {_link_attrs(url, ctx)}>{html.escape(url)}</a>") + trail
        t = URL_RE.sub(bare, t)
    # 5. escape the rest
    t = html.escape(t, quote=False)
    # 6. emphasis
    t = re.sub(r"\*\*(?=\S)(.+?)(?<=\S)\*\*", r"<strong>\1</strong>", t)
    t = re.sub(r"(?<![\w*])\*(?=[^\s*])(.+?)(?<=[^\s*])\*(?![\w*])", r"<em>\1</em>", t)
    # 7. hard line breaks are not part of the contract: soft-wrap lines
    t = t.replace("\n", " ")

    def restore(s: str) -> str:
        return re.sub(r"\x00(\d+)\x00", lambda m: restore(slots[int(m.group(1))]), s)
    return restore(t)


def split_cells(row: str) -> list[str]:
    s = row.strip()
    if s.startswith("|"):
        s = s[1:]
    if s.endswith("|") and not s.endswith("\\|"):
        s = s[:-1]
    cells, cur, in_code, i = [], [], 0, 0
    while i < len(s):
        ch = s[i]
        if ch == "\\" and i + 1 < len(s) and s[i + 1] == "|":
            cur.append("\\|")
            i += 2
            continue
        if ch == "`":
            run = len(s[i:]) - len(s[i:].lstrip("`"))
            if in_code == 0:
                in_code = run
            elif in_code == run:
                in_code = 0
            cur.append("`" * run)
            i += run
            continue
        if ch == "|" and not in_code:
            cells.append("".join(cur).strip())
            cur = []
        else:
            cur.append(ch)
        i += 1
    cells.append("".join(cur).strip())
    return [c.replace("\\|", "|") if "`" in c else c for c in cells]


def is_block_start(line: str) -> bool:
    return bool(FENCE_RE.match(line) or HEADING_RE.match(line) or HR_RE.match(line)
                or QUOTE_RE.match(line) or LIST_RE.match(line))


def code_block(lang: str, code: str) -> str:
    lang = lang.lower()
    cls = f' class="language-{html.escape(lang)}"' if lang else ""
    label = html.escape(lang) if lang else "text"
    return (f'<div class="code-block"><div class="code-bar"><span class="code-lang">{label}</span>'
            f'<button class="copy-btn" type="button" hidden aria-label="Copy code">Copy</button></div>'
            f'<pre><code{cls}>{html.escape(code)}</code></pre></div>')


def render_table(rows: list[str], ctx: RenderCtx) -> str:
    head = split_cells(rows[0])
    aligns = []
    for c in split_cells(rows[1]):
        c = c.strip()
        aligns.append("center" if c.startswith(":") and c.endswith(":") else
                      "right" if c.endswith(":") else "left" if c.startswith(":") else "")
    ncol = len(head)

    def cell(tag, text, idx):
        a = aligns[idx] if idx < len(aligns) else ""
        style = f' style="text-align:{a}"' if a else ""
        return f"<{tag}{style}>{render_inline(text, ctx)}</{tag}>"

    out = [f'<div class="table-wrap" role="region" aria-label="Table" tabindex="0"><table class="cols-{min(ncol, 6)}">',
           "<thead><tr>" + "".join(cell("th", h, i) for i, h in enumerate(head)) + "</tr></thead><tbody>"]
    for r in rows[2:]:
        cells = split_cells(r)
        cells = (cells + [""] * ncol)[:ncol]
        out.append("<tr>" + "".join(cell("td", c, i) for i, c in enumerate(cells)) + "</tr>")
    out.append("</tbody></table></div>")
    return "".join(out)


def render_blocks(lines: list[str], ctx: RenderCtx, depth: int = 0) -> str:
    out: list[str] = []
    i, n = 0, len(lines)
    while i < n:
        line = lines[i]
        if not line.strip():
            i += 1
            continue

        m = FENCE_RE.match(line)
        if m:
            ind, fence, lang = len(m.group(1)), m.group(2), m.group(3)
            close = re.compile(r"^\s*" + re.escape(fence[0]) + "{" + str(len(fence)) + r",}\s*$")
            i += 1
            code = []
            while i < n and not close.match(lines[i]):
                ln = lines[i]
                code.append(ln[min(ind, indent_of(ln)):] if ln.strip() else "")
                i += 1
            if i >= n:
                ctx.warnings.append("unclosed code fence")
            i += 1
            while code and not code[-1].strip():
                code.pop()
            out.append(code_block(lang, "\n".join(code)))
            continue

        m = HEADING_RE.match(line)
        if m:
            level = len(m.group(1))
            text = m.group(2)
            if level == 1:
                ctx.warnings.append(f"'# {text}' heading: the title renders as h1; rendered as h2")
                level = 2
            level = min(level, 4)
            hid = ctx.unique_id(slugify(strip_inline_md(text)))
            inner = render_inline(text, ctx)
            if level in (2, 3) and depth == 0:
                ctx.toc.append((level, hid, strip_inline_md(text)))
            out.append(f'<h{level} id="{hid}"><a class="anchor" href="#{hid}" aria-hidden="true" tabindex="-1">#</a>{inner}</h{level}>')
            i += 1
            continue

        if HR_RE.match(line) and not LIST_RE.match(line):
            out.append("<hr>")
            i += 1
            continue

        if line.lstrip().startswith("|") and i + 1 < n and TABLE_SEP_RE.match(lines[i + 1]):
            rows = [line, lines[i + 1]]
            i += 2
            while i < n and lines[i].strip().startswith("|"):
                rows.append(lines[i])
                i += 1
            out.append(render_table(rows, ctx))
            continue

        if QUOTE_RE.match(line):
            inner = []
            while i < n:
                qm = QUOTE_RE.match(lines[i])
                if qm:
                    inner.append(qm.group(1))
                elif lines[i].strip() and inner and inner[-1].strip() and not is_block_start(lines[i]):
                    inner.append(lines[i].strip())        # lazy continuation
                else:
                    break
                i += 1
            out.append(render_quote(inner, ctx, depth))
            continue

        lm = LIST_RE.match(line)
        if lm:
            html_list, i = render_list(lines, i, ctx, depth)
            out.append(html_list)
            continue

        para = [line.strip()]
        i += 1
        while i < n and lines[i].strip() and not is_block_start(lines[i]) and not (
                lines[i].lstrip().startswith("|") and i + 1 < n and TABLE_SEP_RE.match(lines[i + 1])):
            para.append(lines[i].strip())
            i += 1
        out.append(f"<p>{render_inline(chr(10).join(para), ctx)}</p>")
    return "\n".join(out)


def render_quote(inner: list[str], ctx: RenderCtx, depth: int) -> str:
    first = next((l for l in inner if l.strip()), "")
    cm = re.match(r"^\s*\*\*(" + "|".join(CALLOUTS) + r"):?\*\*:?\s*", first)
    if cm:
        kind = cm.group(1)
        idx = inner.index(first)
        rest = list(inner)
        rest[idx] = first[cm.end():]
        body = render_blocks(rest, ctx, depth + 1)
        return (f'<aside class="callout callout-{kind.lower()}" role="note">'
                f'<p class="callout-label">{kind}</p>{body}</aside>')
    return f"<blockquote>{render_blocks(inner, ctx, depth + 1)}</blockquote>"


def render_list(lines: list[str], i: int, ctx: RenderCtx, depth: int):
    n = len(lines)
    m = LIST_RE.match(lines[i])
    base = len(m.group(1))
    ordered = m.group(2)[0].isdigit()
    start = int(m.group(2)[:-1]) if ordered else 1
    items: list[list[str]] = []

    def sibling(k: int) -> bool:
        mm = LIST_RE.match(lines[k])
        return bool(mm) and indent_of(lines[k]) <= base + 1 and mm.group(2)[0].isdigit() == ordered

    while i < n and sibling(i):
        mm = LIST_RE.match(lines[i])
        content_indent = len(mm.group(1)) + len(mm.group(2)) + min(len(mm.group(3)), 4)
        item = [mm.group(4)]
        i += 1
        while i < n:
            ln = lines[i]
            if not ln.strip():
                j = i
                while j < n and not lines[j].strip():
                    j += 1
                if j < n and indent_of(lines[j]) > base + 1:
                    item.extend([""] * (j - i))     # blank line inside the item
                    i = j
                    continue
                break
            ind = indent_of(ln)
            if ind > base + 1:
                item.append(ln[min(ind, content_indent):])
                i += 1
                continue
            if is_block_start(ln) or (ln.lstrip().startswith("|") and i + 1 < n and TABLE_SEP_RE.match(lines[i + 1])):
                break
            item.append(ln.strip())                  # lazy continuation
            i += 1
        items.append(item)
        # a blank gap followed by another sibling item keeps the list going
        j = i
        while j < n and not lines[j].strip():
            j += 1
        if j < n and j != i and sibling(j):
            i = j

    parts = []
    for item in items:
        if item and (FENCE_RE.match(item[0]) or HEADING_RE.match(item[0]) or QUOTE_RE.match(item[0])
                     or LIST_RE.match(item[0])):
            parts.append(f"<li>{render_blocks(item, ctx, depth + 1)}</li>")
            continue
        k = 0
        while k < len(item) and item[k].strip() and not (k > 0 and is_block_start(item[k])):
            k += 1
        body = render_inline("\n".join(l.strip() for l in item[:k]), ctx)
        if any(r.strip() for r in item[k:]):
            body += render_blocks(item[k:], ctx, depth + 1)
        parts.append(f"<li>{body}</li>")
    tag = "ol" if ordered else "ul"
    st = f' start="{start}"' if ordered and start != 1 else ""
    return f"<{tag}{st}>" + "".join(parts) + f"</{tag}>", i


def markdown_to_html(body: str):
    ctx = RenderCtx()
    lines = body.replace("\r\n", "\n").replace("\t", "    ").split("\n")
    return render_blocks(lines, ctx), ctx


def plain_text(body: str) -> str:
    """Prose text of a Markdown body, for search and reading time."""
    t = re.sub(r"^(\s*)(`{3,}|~{3,}).*?^\s*\2\s*$", " ", body, flags=re.S | re.M)
    t = re.sub(r"^\s*\|?\s*:?-{2,}.*$", " ", t, flags=re.M)
    t = re.sub(r"^\s{0,3}#{1,6}\s+", "", t, flags=re.M)
    t = re.sub(r"^\s*>\s?", "", t, flags=re.M)
    t = re.sub(r"^\s*([-*+]|\d+[.)])\s+", "", t, flags=re.M)
    t = t.replace("|", " ")
    t = strip_inline_md(t)
    return re.sub(r"\s+", " ", t).strip()


# --------------------------------------------------------------------------
# Model
# --------------------------------------------------------------------------

@dataclass
class Article:
    section: str
    slug: str
    title: str
    description: str
    group: str
    order: int
    updated: str
    src: Path
    body_html: str = ""
    toc: list = field(default_factory=list)
    links: list = field(default_factory=list)
    text: str = ""
    minutes: int = 1
    headings: list = field(default_factory=list)

    @property
    def url(self) -> str:
        return f"/docs/{self.section}/{self.slug}/"


@dataclass
class Section:
    id: str
    title: str
    description: str
    groups: list
    articles: list = field(default_factory=list)
    cta: dict = field(default_factory=dict)

    @property
    def url(self) -> str:
        return f"/docs/{self.id}/"

    def grouped(self):
        """[(group label or '', [articles])] in display order."""
        buckets: dict[str, list] = {}
        for a in self.articles:
            buckets.setdefault(a.group or "", []).append(a)
        order = [""] + list(self.groups) + sorted(g for g in buckets if g and g not in self.groups)
        out = []
        for g in order:
            if g in buckets:
                out.append((g, sorted(buckets[g], key=lambda a: (a.order, a.slug))))
        return out

    def ordered(self):
        return [a for _, arts in self.grouped() for a in arts]

    @property
    def tier(self):
        m = re.match(r"^(Tier \d+)\.\s*(.*)$", self.description)
        return (m.group(1), m.group(2)) if m else ("", self.description)


def load_sections(path: Path) -> list[Section]:
    try:
        data = json.loads(path.read_text())
    except (OSError, json.JSONDecodeError) as e:
        raise SystemExit(f"cannot read sections file {path}: {e}")
    secs, seen = [], set()
    for s in data:
        sid = s["id"]
        if not SLUG_RE.match(sid) or sid in seen:
            raise SystemExit(f"sections.json: bad or duplicate id {sid!r}")
        seen.add(sid)
        secs.append(Section(sid, s["title"], s.get("description", ""), list(s.get("groups") or []), cta=dict(s.get("cta") or {})))
    return secs


def load_articles(content: Path, sections: list[Section], errors: list[str], warnings: list[str]):
    by_id = {s.id: s for s in sections}
    for path in sorted(content.glob("**/*.md")):
        rel = path.relative_to(content)
        try:
            if len(rel.parts) != 2:
                raise SourceError("must live at content/<section>/<slug>.md")
            folder, slug = rel.parts[0], path.stem
            meta, body = parse_front_matter(path.read_text(encoding="utf-8"))
            extra = set(meta) - ALLOWED_KEYS
            if extra:
                raise SourceError(f"unknown front matter keys: {sorted(extra)}")
            missing = [k for k in REQUIRED_KEYS if meta.get(k) in (None, "")]
            if missing:
                raise SourceError(f"missing front matter: {missing}")
            if meta["section"] != folder:
                raise SourceError(f"section {meta['section']!r} does not match folder {folder!r}")
            if folder not in by_id:
                raise SourceError(f"section {folder!r} is not in sections.json")
            if not SLUG_RE.match(slug):
                raise SourceError(f"slug {slug!r} is not lowercase-kebab")
            if not isinstance(meta["order"], int):
                raise SourceError("order must be an integer")
            if not DATE_RE.match(str(meta["updated"])):
                raise SourceError("updated must be YYYY-MM-DD")
            title, desc = str(meta["title"]).strip(), str(meta["description"]).strip()
            if len(desc) >= 160:
                warnings.append(f"{rel}: description is {len(desc)} chars (contract: under 160)")
        except SourceError as e:
            errors.append(f"{rel}: {e}")
            continue
        a = Article(folder, slug, title, desc, str(meta.get("group") or "").strip(),
                    meta["order"], str(meta["updated"]), path)
        a.body_html, ctx = markdown_to_html(body)
        a.toc, a.links = ctx.toc, ctx.links
        for w in ctx.warnings:
            warnings.append(f"{rel}: {w}")
        a.text = plain_text(body)
        a.minutes = max(1, math.ceil(len(a.text.split()) / WORDS_PER_MIN))
        a.headings = [t for lvl, _, t in a.toc]
        sec = by_id[folder]
        if a.group and a.group not in sec.groups:
            warnings.append(f"{rel}: group {a.group!r} is not listed in sections.json for {folder}")
        sec.articles.append(a)


# --------------------------------------------------------------------------
# Page templates
# --------------------------------------------------------------------------

E = lambda s: html.escape(str(s), quote=True)  # noqa: E731

SITE_NAV = [
    ("Nerve Center", "/#nerve-center"),
    ("Builds", "/#builds"),
    ("Experience", "/#enterprise"),
    ("Docs", "/docs/"),
    ("Contact", "/#contact"),
]

FOOTER_LINKS = [
    ("LinkedIn", "https://www.linkedin.com/in/jd-davenport/", True),
    ("GitHub", "https://github.com/jddavenportOpen", True),
    ("Docs", "/docs/", False),
    ("Newsletter", "https://docs.agenttree.army/newsletter", True),
    ("Book", "https://book.jddavenport.com", False),
    ("Email", "mailto:me@jddavenport.com", False),
]


def head(title: str, description: str, url: str, og_type: str = "article") -> str:
    canon = SITE + url
    return f"""<!DOCTYPE html>
<html lang="en">
<head>
{GENERATED_MARK}
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<title>{E(title)}</title>
<meta name="description" content="{E(description)}">
<link rel="canonical" href="{E(canon)}">
<meta property="og:type" content="{og_type}">
<meta property="og:site_name" content="JD Davenport">
<meta property="og:url" content="{E(canon)}">
<meta property="og:title" content="{E(title)}">
<meta property="og:description" content="{E(description)}">
<meta property="og:image" content="{OG_IMAGE}">
<meta name="twitter:card" content="summary_large_image">
<meta name="twitter:title" content="{E(title)}">
<meta name="twitter:description" content="{E(description)}">
<meta name="twitter:image" content="{OG_IMAGE}">
<link rel="icon" type="image/svg+xml" href="/favicon.svg">
<script defer src="/_vercel/insights/script.js"></script>
<link rel="preconnect" href="https://fonts.googleapis.com">
<link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
<link href="https://fonts.googleapis.com/css2?family=Geist:wght@400;500;600;700&family=Geist+Mono:wght@400;500;600&display=swap" rel="stylesheet">
<link rel="stylesheet" href="/docs/docs.css">
<script>document.documentElement.classList.add('js')</script>
<script defer src="/docs/docs.js"></script>
</head>"""


def site_header() -> str:
    links = []
    for label, href in SITE_NAV:
        cur = ' aria-current="page" class="active"' if label == "Docs" else ""
        links.append(f'<a href="{href}"{cur}>{label}</a>')
    links.append('<a href="https://www.linkedin.com/in/jd-davenport/" target="_blank" rel="noopener" class="btn btn-primary">Connect →</a>')
    return f"""<a class="skip-link" href="#main">Skip to content</a>
<header class="site-header" id="header">
  <div class="header-inner">
    <a href="/" class="logo"><span class="dot"></span>jd_davenport</a>
    <button class="nav-toggle" id="navToggle" type="button" aria-label="Toggle navigation" aria-expanded="false" aria-controls="siteNav"><span class="bars" aria-hidden="true"></span></button>
    <nav id="siteNav" aria-label="Site">
      {"".join(links)}
    </nav>
  </div>
</header>"""


def site_footer() -> str:
    links = []
    for label, href, ext in FOOTER_LINKS:
        extra = ' target="_blank" rel="noopener"' if ext else ""
        links.append(f'<a href="{href}"{extra}>{label}</a>')
    return f"""<footer class="site-footer">
  <div class="footer-inner">
    <div class="footer-links">{"".join(links)}</div>
    <div class="wordmark">JD Davenport</div>
    <div class="footer-copy">© 2026 · built in the warm-graphite system</div>
  </div>
</footer>"""


def search_box(variant: str) -> str:
    big = " search-lg" if variant == "landing" else ""
    sid = f"docs-search-{variant}"
    return f"""<div class="search{big}" data-search hidden>
  <label class="sr-only" for="{sid}">Search the docs</label>
  <div class="search-field">
    <svg class="search-icon" viewBox="0 0 16 16" aria-hidden="true"><circle cx="7" cy="7" r="4.6" fill="none" stroke="currentColor" stroke-width="1.5"/><path d="M10.5 10.5 14 14" stroke="currentColor" stroke-width="1.5" stroke-linecap="round"/></svg>
    <input id="{sid}" type="search" placeholder="Search the docs" autocomplete="off" spellcheck="false" role="combobox" aria-expanded="false" aria-controls="{sid}-results" aria-autocomplete="list">
    <kbd class="search-kbd" aria-hidden="true">/</kbd>
  </div>
  <ul class="search-results" id="{sid}-results" role="listbox" hidden></ul>
  <p class="search-status sr-only" aria-live="polite"></p>
</div>"""


def sidebar(sections: list[Section], cur_section: str, cur_url: str) -> str:
    parts = ['<aside class="docs-sidebar" id="docsSidebar" aria-label="Docs navigation">',
             '<div class="sidebar-inner">',
             '<div class="sidebar-top"><a class="sidebar-home" href="/docs/">Docs home</a>'
             '<button class="drawer-close" type="button" id="drawerClose" aria-label="Close menu"><span aria-hidden="true"></span></button></div>',
             search_box("sidebar"), '<nav class="tree" aria-label="Sections">']
    for s in sections:
        if not s.articles:
            continue
        is_cur = s.id == cur_section
        opn = " open" if is_cur else ""
        parts.append(f'<details class="tree-section"{opn}><summary>{E(s.title)}</summary>')
        ov = ' aria-current="page"' if cur_url == s.url else ""
        parts.append(f'<ul><li><a href="{s.url}"{ov}>Overview</a></li></ul>')
        for g, arts in s.grouped():
            if g:
                parts.append(f'<p class="tree-group">{E(g)}</p>')
            parts.append("<ul>")
            for a in arts:
                c = ' aria-current="page"' if a.url == cur_url else ""
                parts.append(f'<li><a href="{a.url}"{c}>{E(a.title)}</a></li>')
            parts.append("</ul>")
        parts.append("</details>")
    parts.append("</nav></div></aside>")
    return "\n".join(parts)


def docs_bar(label: str) -> str:
    return f"""<div class="docs-bar">
  <button class="docs-menu-btn" id="docsMenuBtn" type="button" aria-expanded="false" aria-controls="docsSidebar"><span class="menu-icon" aria-hidden="true"></span>Menu</button>
  <span class="docs-bar-label">{E(label)}</span>
</div>
<div class="drawer-overlay" id="drawerOverlay" hidden></div>"""


def breadcrumb(items: list[tuple[str, str | None]]) -> str:
    out = []
    for label, href in items:
        out.append(f'<li><a href="{href}">{E(label)}</a></li>' if href else f'<li aria-current="page">{E(label)}</li>')
    return f'<nav class="breadcrumb" aria-label="Breadcrumb"><ol>{"".join(out)}</ol></nav>'


def fmt_date(d: str) -> str:
    return d


def article_page(a: Article, sec: Section, sections: list[Section], prev: Article | None, nxt: Article | None) -> str:
    sec_by = {s.id: s for s in sections}
    toc = ""
    if len(a.toc) >= 2:
        items = "".join(f'<li class="toc-l{lvl}"><a href="#{hid}">{E(t)}</a></li>' for lvl, hid, t in a.toc)
        toc = f'<aside class="docs-toc" aria-label="On this page"><div class="toc-inner"><p class="toc-title">On this page</p><ul>{items}</ul></div></aside>'
    pn = []
    if prev:
        ps = "" if prev.section == a.section else f" · {sec_by[prev.section].title}"
        pn.append(f'<a class="pn pn-prev" href="{prev.url}" rel="prev"><span class="pn-dir">← Previous{E(ps)}</span><span class="pn-title">{E(prev.title)}</span></a>')
    else:
        pn.append('<span class="pn pn-empty" aria-hidden="true"></span>')
    if nxt:
        ns = "" if nxt.section == a.section else f" · {sec_by[nxt.section].title}"
        pn.append(f'<a class="pn pn-next" href="{nxt.url}" rel="next"><span class="pn-dir">Next{E(ns)} →</span><span class="pn-title">{E(nxt.title)}</span></a>')
    crumbs = [("Docs", "/docs/"), (sec.title, sec.url)]
    kicker = a.group or sec.title
    return f"""{head(f"{a.title} · JD Davenport Docs", a.description, a.url)}
<body class="docs docs-article">
{site_header()}
{docs_bar(sec.title)}
<div class="docs-layout{' has-toc' if toc else ''}">
{sidebar(sections, sec.id, a.url)}
<main id="main" class="docs-main">
<article class="doc">
  {breadcrumb(crumbs)}
  <div class="kicker">{E(kicker)}</div>
  <h1>{E(a.title)}</h1>
  <p class="doc-lead">{E(a.description)}</p>
  <p class="doc-meta"><span>Updated <time datetime="{E(a.updated)}">{E(fmt_date(a.updated))}</time></span><span aria-hidden="true">·</span><span>{a.minutes} min read</span></p>
  <div class="prose">
{a.body_html}
  </div>
  {cta_block(sec)}
  <nav class="prev-next" aria-label="Previous and next">{"".join(pn)}</nav>
</article>
</main>
{toc}
</div>
{site_footer()}
</body>
</html>
"""


def cta_block(sec: Section, compact: bool = False) -> str:
    """Series call to action, configured per section in sections.json ("cta")."""
    c = sec.cta
    if not c or not c.get("url"):
        return ""
    cls = "series-cta compact" if compact else "series-cta"
    return (f'<aside class="{cls}" aria-label="{E(c.get("title", "Join the series"))}">'
            f'<div class="kicker">{E(c.get("kicker", "Join the series"))}</div>'
            f'<p class="series-cta-title">{E(c.get("title", ""))}</p>'
            f'<p class="series-cta-text">{E(c.get("text", ""))}</p>'
            f'<a class="btn btn-primary" href="{E(c["url"])}" target="_blank" rel="noopener">{E(c.get("label", "Open the post"))} ↗</a>'
            f'</aside>')


def article_card(a: Article) -> str:
    return (f'<li><a class="doc-card" href="{a.url}"><span class="doc-card-title">{E(a.title)}</span>'
            f'<span class="doc-card-desc">{E(a.description)}</span>'
            f'<span class="doc-card-meta">{a.minutes} min read</span></a></li>')


def section_page(sec: Section, sections: list[Section]) -> str:
    tier, desc = sec.tier
    blocks = []
    for g, arts in sec.grouped():
        if g:
            gid = slugify(g)
            blocks.append(f'<h2 id="{gid}" class="group-title">{E(g)}</h2>')
        blocks.append('<ol class="card-list">' + "".join(article_card(a) for a in arts) + "</ol>")
    first = sec.ordered()[0]
    n = len(sec.articles)
    return f"""{head(f"{sec.title} · JD Davenport Docs", sec.description, sec.url, "website")}
<body class="docs docs-section">
{site_header()}
{docs_bar(sec.title)}
<div class="docs-layout">
{sidebar(sections, sec.id, sec.url)}
<main id="main" class="docs-main">
<div class="doc">
  {breadcrumb([("Docs", "/docs/"), (sec.title, None)])}
  <div class="kicker">{E(tier or "Section")}</div>
  <h1>{E(sec.title)}</h1>
  <p class="doc-lead">{E(desc)}</p>
  <p class="doc-meta"><span>{n} article{'s' if n != 1 else ''}</span><span aria-hidden="true">·</span><span>{sum(a.minutes for a in sec.articles)} min total</span></p>
  <p class="section-start"><a class="btn btn-primary" href="{first.url}">Start reading →</a></p>
  {cta_block(sec)}
  {"".join(blocks)}
</div>
</main>
</div>
{site_footer()}
</body>
</html>
"""


def landing_page(sections: list[Section]) -> str:
    live = [s for s in sections if s.articles]
    featured = next((s for s in live if s.id == "ai-core-skills"), None)
    feat_html = ""
    if featured:
        groups = []
        for g, arts in featured.grouped():
            items = "".join(
                f'<li><a href="{a.url}"><span class="fl-n">{k:02d}</span><span class="fl-t">{E(a.title)}</span></a></li>'
                for k, a in enumerate(arts, 1))
            label = f'<p class="feat-group">{E(g)}</p>' if g else ""
            groups.append(f'{label}<ol class="feat-list">{items}</ol>')
        first = featured.ordered()[0]
        feat_html = f"""<section class="featured" aria-labelledby="feat-title">
    <div class="feat-copy">
      <div class="kicker">Featured · new series</div>
      <h2 id="feat-title">{E(featured.title)}</h2>
      <p>{E(featured.description)}</p>
      <div class="feat-ctas"><a class="btn btn-primary" href="{first.url}">Start reading →</a><a class="btn btn-outline" href="{featured.url}">Section overview</a></div>
      {cta_block(featured, compact=True)}
    </div>
    <div class="feat-index">{"".join(groups)}</div>
  </section>"""
    cards = []
    for s in live:
        if featured and s.id == featured.id:
            continue
        tier, desc = s.tier
        n = len(s.articles)
        cards.append(f"""<li><a class="section-card" href="{s.url}">
      <span class="sc-kicker">{E(tier or "Section")}</span>
      <span class="sc-title">{E(s.title)}</span>
      <span class="sc-desc">{E(desc)}</span>
      <span class="sc-meta">{n} article{'s' if n != 1 else ''} →</span>
    </a></li>""")
    desc = ("How I build and run a production AI organization with Claude Code, from a first install "
            "to 30+ agents in daily production, plus AI Core Skills: one in-demand skill at a time.")
    total = sum(len(s.articles) for s in live)
    return f"""{head("Docs · JD Davenport", desc, "/docs/", "website")}
<body class="docs docs-landing">
{site_header()}
<main id="main" class="landing">
  <section class="landing-hero">
    <div class="kicker">Docs</div>
    <h1>How I build and run agents in production.</h1>
    <p class="landing-sub">Claude Code from a first install to an AI organization with <strong>30+ agents in daily production, 100+ built over time.</strong> What works, what broke, and the fix that kept it from breaking again. Rewritten for October 2026.</p>
    {search_box("landing")}
    <p class="landing-meta mono">{total} articles · {len(live)} sections · updated {max((a.updated for s in live for a in s.articles), default="")}</p>
  </section>
  {feat_html}
  <section class="sections" aria-labelledby="sections-title">
    <div class="kicker">Sections</div>
    <h2 id="sections-title" class="sections-title">Read in order, or jump to what you need</h2>
    <ul class="section-grid">
    {"".join(cards)}
    </ul>
  </section>
</main>
{site_footer()}
</body>
</html>
"""


# --------------------------------------------------------------------------
# Output
# --------------------------------------------------------------------------

def write_if_changed(path: Path, data: str | bytes, written: list[Path]) -> bool:
    raw = data.encode("utf-8") if isinstance(data, str) else data
    path.parent.mkdir(parents=True, exist_ok=True)
    written.append(path)
    if path.exists() and path.read_bytes() == raw:
        return False
    path.write_bytes(raw)
    return True


def prune_stale(keep: set[Path], quiet: bool) -> list[Path]:
    """Delete generated pages under docs/ that this build no longer produces.

    Only files carrying GENERATED_MARK are candidates, and only under OUT.
    """
    removed = []
    out_real = OUT.resolve()
    for p in sorted(OUT.rglob("index.html")):
        rp = p.resolve()
        if out_real not in rp.parents or rp in keep:
            continue
        try:
            head_txt = p.read_text(encoding="utf-8", errors="replace")[:600]
        except OSError:
            continue
        if GENERATED_MARK not in head_txt:
            continue
        p.unlink()
        removed.append(p)
    # remove now-empty directories, deepest first, never OUT itself
    for d in sorted((d for d in OUT.rglob("*") if d.is_dir()), key=lambda d: len(d.parts), reverse=True):
        if d.resolve() != out_real and out_real in d.resolve().parents and not any(d.iterdir()):
            d.rmdir()
    if removed and not quiet:
        for p in removed:
            print(f"  removed stale {p.relative_to(ROOT)}")
    return removed


def update_sitemap(urls: list[tuple[str, str]]) -> bool:
    if not SITEMAP.exists():
        return False
    src = SITEMAP.read_text(encoding="utf-8")
    # drop every existing docs <url> entry, keep everything else byte-for-byte
    pat = re.compile(r"[ \t]*<url>\s*<loc>" + re.escape(SITE) + r"/docs/[^<]*</loc>.*?</url>\s*\n?", re.S)
    kept = pat.sub("", src)
    entries = []
    for url, lastmod in urls:
        pri = "0.8" if url == "/docs/" else "0.7" if url.count("/") == 3 else "0.6"
        entries.append(f"  <url>\n    <loc>{SITE}{url}</loc>\n    <lastmod>{lastmod}</lastmod>\n"
                       f"    <changefreq>monthly</changefreq>\n    <priority>{pri}</priority>\n  </url>\n")
    idx = kept.rfind("</urlset>")
    if idx < 0:
        raise SystemExit("sitemap.xml has no </urlset>")
    new = kept[:idx] + "".join(entries) + kept[idx:]
    if new != src:
        SITEMAP.write_text(new, encoding="utf-8")
        return True
    return False


def build(sections_path: Path, content: Path, quiet: bool = False, sitemap: bool = True) -> int:
    errors: list[str] = []
    warnings: list[str] = []
    sections = load_sections(sections_path)
    load_articles(content, sections, errors, warnings)
    live = [s for s in sections if s.articles]

    ordered = [a for s in live for a in s.ordered()]
    written: list[Path] = []
    changed = 0
    OUT.mkdir(exist_ok=True)

    for asset in ("docs.css", "docs.js"):
        changed += write_if_changed(OUT / asset, (ASSETS / asset).read_bytes(), written)

    changed += write_if_changed(OUT / "index.html", landing_page(sections), written)
    for s in live:
        changed += write_if_changed(OUT / s.id / "index.html", section_page(s, sections), written)
    for k, a in enumerate(ordered):
        prev = ordered[k - 1] if k > 0 else None
        nxt = ordered[k + 1] if k + 1 < len(ordered) else None
        sec = next(s for s in live if s.id == a.section)
        changed += write_if_changed(OUT / a.section / a.slug / "index.html",
                                    article_page(a, sec, sections, prev, nxt), written)

    index = []
    for a in ordered:
        sec = next(s for s in live if s.id == a.section)
        index.append({"title": a.title, "description": a.description, "section": sec.title,
                      "group": a.group, "url": a.url, "headings": a.headings, "text": a.text[:400]})
    for s in live:
        index.append({"title": s.title, "description": s.tier[1], "section": "Section", "group": "",
                      "url": s.url, "headings": [g for g, _ in s.grouped() if g], "text": ""})
    changed += write_if_changed(OUT / "search-index.json",
                                json.dumps(index, ensure_ascii=False, separators=(",", ":")) + "\n", written)

    removed = prune_stale({p.resolve() for p in written}, quiet)

    sm_changed = False
    if sitemap:
        newest = max((a.updated for a in ordered), default="2026-10-05")
        urls = [("/docs/", newest)]
        for s in live:
            urls.append((s.url, max(a.updated for a in s.articles)))
            urls.extend((a.url, a.updated) for a in s.ordered())
        sm_changed = update_sitemap(urls)

    for w in warnings:
        print(f"WARN  {w}", file=sys.stderr)
    for e in errors:
        print(f"ERROR {e}  (skipped)", file=sys.stderr)
    if not quiet:
        print(f"docs: {len(ordered)} articles in {len(live)} sections · {changed} files changed · "
              f"{len(removed)} stale removed · sitemap {'updated' if sm_changed else 'unchanged'} · "
              f"{len(warnings)} warnings · {len(errors)} errors")
    return 1 if errors else 0


def main() -> int:
    ap = argparse.ArgumentParser(description=__doc__.split("\n")[0])
    ap.add_argument("--sections", type=Path, default=DEFAULT_SECTIONS)
    ap.add_argument("--content", type=Path, default=DEFAULT_CONTENT)
    ap.add_argument("--no-sitemap", action="store_true", help="do not touch sitemap.xml")
    ap.add_argument("--quiet", action="store_true")
    args = ap.parse_args()
    return build(args.sections, args.content, quiet=args.quiet, sitemap=not args.no_sitemap)


if __name__ == "__main__":
    sys.exit(main())
