// GET /api/metrics
//
// Server-side proxy for the public capabilities feed that the Nerve Center
// regenerates from its own live state every day:
//   https://nerve-center-showcase.vercel.app/capabilities.json
//
// Why a proxy and not a browser fetch:
//   1. One cache edge. s-maxage=3600 means the showcase gets hit at most once
//      an hour per region no matter how much traffic the homepage takes.
//   2. An explicit allowlist. The upstream file is generated by a separate
//      pipeline and can grow fields at any time; this endpoint forwards only
//      the fields the homepage actually renders, so nothing new leaks onto a
//      public page without a code change here.
//   3. stale-while-revalidate=86400 means a showcase outage never blanks the
//      homepage. The edge keeps serving yesterday's numbers for a day.
//
// Fail-open by design. Every field is optional. The `metrics` block is
// produced by a separate lane and may be absent entirely; when it is, this
// still returns 200 with `stats` so the agent/domain counters stay live.
// The homepage ships baked-in defaults in its HTML and only upgrades a
// number when this endpoint actually hands one over, so no-JS, a failed
// fetch, and a degraded upstream all render a dated snapshot instead of a
// blank.

const UPSTREAM = 'https://nerve-center-showcase.vercel.app/capabilities.json';
const UPSTREAM_TIMEOUT_MS = 6000;

// Allowlist. Anything not named here is dropped, including new upstream keys.
const STAT_KEYS = ['agents', 'skills', 'automations', 'domains', 'ships_last_30d'];
const METRIC_NUMBER_KEYS = [
  'turns_yesterday',
  'usd_equivalent_yesterday',
  'live_users',
  'building_since',
  'incidents_documented',
  'tests_estate',
];

// Date-valued metrics, forwarded only when they are a real ISO day.
const METRIC_DATE_KEYS = ['production_since'];

function num(value) {
  return typeof value === 'number' && Number.isFinite(value) ? value : undefined;
}

function pickNumbers(source, keys) {
  const out = {};
  if (!source || typeof source !== 'object') return out;
  for (const key of keys) {
    const v = num(source[key]);
    if (v !== undefined) out[key] = v;
  }
  return out;
}

// tokens_yesterday is a breakdown object; forward the shape, numbers only.
function pickTokens(source) {
  const t = pickNumbers(source, ['input', 'output', 'cache_read', 'cache_creation', 'total']);
  return Object.keys(t).length ? t : undefined;
}

// The sparkline is the only array forwarded. Capped, and each point is
// reduced to exactly {d, total} so an upstream schema change cannot smuggle
// extra fields onto the page.
function pickSparkline(source) {
  if (!Array.isArray(source)) return undefined;
  const points = source
    .slice(-31)
    .map((p) => {
      if (!p || typeof p !== 'object') return null;
      const total = num(p.total);
      const d = typeof p.d === 'string' ? p.d.slice(0, 10) : undefined;
      if (total === undefined || !d) return null;
      return { d, total };
    })
    .filter(Boolean);
  return points.length ? points : undefined;
}

function pickRepos(source) {
  const r = pickNumbers(source, ['public', 'total', 'accounts']);
  return Object.keys(r).length ? r : undefined;
}

function pickTools(source) {
  const t = pickNumbers(source, ['agents', 'skills', 'automations', 'mcp_servers', 'domains']);
  return Object.keys(t).length ? t : undefined;
}

function isIsoDate(value) {
  return typeof value === 'string' && /^\d{4}-\d{2}-\d{2}$/.test(value);
}

async function fetchUpstream() {
  const controller = new AbortController();
  const timer = setTimeout(() => controller.abort(), UPSTREAM_TIMEOUT_MS);
  try {
    const res = await fetch(UPSTREAM, {
      signal: controller.signal,
      headers: { accept: 'application/json' },
    });
    if (!res.ok) throw new Error(`upstream ${res.status}`);
    return await res.json();
  } finally {
    clearTimeout(timer);
  }
}

module.exports = async function handler(req, res) {
  if (req.method !== 'GET') {
    return res.status(405).json({ error: 'Method not allowed' });
  }

  let upstream;
  try {
    upstream = await fetchUpstream();
  } catch (err) {
    console.error('[metrics] upstream fetch failed:', err.message);
    // Short cache on failure so the next request retries quickly, and the
    // homepage simply keeps its baked-in snapshot.
    res.setHeader('Cache-Control', 's-maxage=60, stale-while-revalidate=3600');
    return res.status(503).json({ error: 'metrics_unavailable' });
  }

  const src = upstream && typeof upstream === 'object' ? upstream : {};
  const rawMetrics = src.metrics && typeof src.metrics === 'object' ? src.metrics : {};

  const metrics = pickNumbers(rawMetrics, METRIC_NUMBER_KEYS);

  const tokens = pickTokens(rawMetrics.tokens_yesterday);
  if (tokens) metrics.tokens_yesterday = tokens;

  const sparkline = pickSparkline(rawMetrics.tokens_30d_sparkline);
  if (sparkline) metrics.tokens_30d_sparkline = sparkline;

  const repos = pickRepos(rawMetrics.repos);
  if (repos) metrics.repos = repos;

  const tools = pickTools(rawMetrics.tools);
  if (tools) metrics.tools = tools;

  for (const key of METRIC_DATE_KEYS) {
    if (isIsoDate(rawMetrics[key])) metrics[key] = rawMetrics[key];
  }

  // as_of: prefer the metrics block's own stamp, fall back to the feed's.
  const asOf = [rawMetrics.as_of, src.last_updated].find(isIsoDate) || null;
  if (asOf) metrics.as_of = asOf;

  res.setHeader('Cache-Control', 's-maxage=3600, stale-while-revalidate=86400');
  return res.status(200).json({
    as_of: asOf,
    source: 'nerve-center-showcase.vercel.app/capabilities.json',
    // `stats` is the always-present half of the feed: it exists today, so the
    // agent/domain/skill counters go live immediately even before the metrics
    // block lands upstream.
    stats: pickNumbers(src.stats, STAT_KEYS),
    // Empty object when the upstream metrics block is not published yet.
    metrics,
  });
};
